### PR TITLE
feat: implemented pint

### LINKED ISSUE #4361: 💄 Add Code Linter To ‘utopia-php/pay’
# 💭 Introduction

Linter is one of the most valuable tools in the open source world. It not only ensures every developer contributes the code with the same style but also allows CI/CD to ensure this. Having a linter set up should be a high priority for every project as it makes source code more readable for future contributors.

Your task is to update our library [utopia-php/pay](https://github.com/utopia-php/pay) and implement a code linter. We would like to use [Pint](https://github.com/laravel/pint) as our linter.

**To make this task easy, we created a sample pull request showing what exactly needs to be done to implement a linter into the Utopia PHP library: [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7)**

### 🎯 Requirements

- Experience with GitHub Actions.
- Experience with Composer.
- Experience with PHP.

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Implement code linter in [utopia-php/pay](https://github.com/utopia-php/pay) (use [https://github.com/utopia-php/ab/pull/7](https://github.com/utopia-php/ab/pull/7) as template)
- [ ]  Submit a pull request in [utopia-php/pay](https://github.com/utopia-php/pay).

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by byt3h3ad**
related to issue [#4361](https://github.com/appwrite/appwrite/issues/4361)

### CODE REVIEW

**Comment by byt3h3ad** [comment]
should i lint the existing files as well and push another commit?

**Comment by Meldiron** [comment]
@byt3h3ad Yes, we need to lint existing files. Please commit those changes.

**Review by Meldiron — CHANGES_REQUESTED** [review]
Looks like there is existing linter in this repository. Can we make sure to remove it fully? This includes removing `phpcs.xml` file, all mentions of `phpcs` in the project, and the same for `phpcbf`. After that please update composer lockfile again.

**Review by Meldiron — CHANGES_REQUESTED** [review]
(Whoops, wrong PR. Deleting this comment 😅)

**Comment by byt3h3ad** [comment]
@Meldiron all changes have been made.

**Review by Meldiron — APPROVED** [review]
Looks great 🎉

**Comment by byt3h3ad** [comment]
:facepalm: accidentally deleted the head repo.

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
